action_dim: 1
annealing: true
annealing_start: 50000
annealing_steps: 1000000
baseline_path: weights.pt
baseline_temp: 0.1
batch: true
count_param: 0.2
dataset_path: dataset/3000/123/1_0/counts_dataset.pkl
dataset_size: 1000
ddqn: true
device: cpu
domain: dummy
dummy_a_max: 1
dummy_log: false
dummy_noise: 0.025
dummy_noise_v: 0.05
dummy_size: 3
dummy_time_step: 0.1
dummy_v_max: 1
episode_max_len: 100
epsilon: 1.0
epsilon_soft: 1.0
extra_stochasticity: 0.0
final_epsilon: 0.1
folder_location: ./baseline/
folder_name: dummy_env_keras
gamma: 0.9
history_len: 1
is_learning: true
is_testing: true
kappa: 0.003
learning_frequency: 10
learning_rate: 0.01
learning_type: pi_b
max_start_nullops: 0
minibatch_size: 32
minimum_count: 100000.0
nb_actions: 9
network_path: weights.pt
network_size: dense
noise_factor: 1
normalize: 1.0
num_epochs: 1
num_experiments: 15
passes_on_dataset: 1
replay_max_size: 1000000
replay_min_size: 1
reward_dim: 1
seed: 123
state_shape: [4]
steps_per_epoch: 10000
steps_per_test: 1000
test: false
test_epsilon: 0.0
update_freq: 10
